# Generated by Django 5.0.7 on 2024-07-21 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentGeneration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('input_context', models.TextField()),
                ('content_output', models.TextField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
