# Generated by Django 5.0.7 on 2024-07-21 14:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentgeneration',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
